apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-statefulset.fullname" . }}-mysql-secret
type: Opaque
data:
  MYSQL_DATABASE: {{ .Values.secret.MYSQL_DATABASE | default "bXlEQg==" }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD | default "cm9vdA==" }}
  MYSQL_USER: {{ .Values.secret.MYSQL_USER | default "YWRtaW4=" }}
  MYSQL_PASSWORD: {{ .Values.secret.MYSQL_PASSWORD | default "YWRtaW4=" }}
