# confipmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "two-tier-flask-app.fullname" . }}
data:
  MYSQL_HOST: {{ .Values.configMap.MYSQL_HOST | default "mysql-service" }}
  MYSQL_DB: {{ .Values.configMap.MYSQL_DB | default "myDb" }}
