apiVersion: v1
kind: Secret
metadata:
  name: {{ include "two-tier-flask-app.fullname" . }}
type: Opaque
data:
  MYSQL_USER: {{ .Values.secret.MYSQL_USER | default "YWRtaW4=" }}
  MYSQL_PASSWORD: {{ .Values.secret.MYSQL_PASSWORD | default "YWRtaW4=" }}
