apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # Codificado en base 64
  MYSQL_USER: YWRtaW4=  # Codificado en base 64
  MYSQL_PASSWORD: YWRtaW4=  # Codificado en base 64
